"""add column count in order_product_many

Revision ID: cb549e53f9ee
Revises: 3dff5cbec5fc
Create Date: 2024-04-16 11:23:19.265186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb549e53f9ee'
down_revision: Union[str, None] = '3dff5cbec5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_many', sa.Column('count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_many', 'count')
    # ### end Alembic commands ###
