"""add column unit_price in OrderProductMany

Revision ID: 8c15e5f497db
Revises: cb549e53f9ee
Create Date: 2024-04-16 12:09:54.162032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c15e5f497db'
down_revision: Union[str, None] = 'cb549e53f9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_many', sa.Column('unit_price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_many', 'unit_price')
    # ### end Alembic commands ###
